# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = 2

ENV['BIGIP_LICENSE'] ||= ''
ENV['BIGIP_PORT'] ||= '10443'
ENV['BIGIP_NAME'] ||= 'big-ip01.internal'
ENV['BOX_URL'] ||=  './BIGIP-13.0.0.0.0.1645.box'

WAIT_FOR_BIGIP = <<SHELL
for retries in {1..100} ; do
    # Retry until mcpd completes startup
    tmsh -a show sys mcp-state field-fmt 2>/dev/null | grep phase | grep running
    rc=$?
    if [ $rc -eq 0 ]; then break ; fi
    sleep 30
done

if [ $rc -ne 0 ]; then
    /usr/bin/tmsh -a show sys mcp-state field-fmt
fi
echo "Runlevel is now valid, kicking off provisioning..."
sleep 5
SHELL

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.boot_timeout = 3600

  config.vm.define ENV['BIGIP_NAME'] do |v|
    v.vm.box = ENV['BOX_URL']

    # BIG-IP cannot mount shares in Virtualbox because Guest-Additions
    # cannot be installed on it.
    v.vm.synced_folder ".", "/vagrant", disabled: true
    v.vm.network :forwarded_port, guest: 443, host: ENV['BIGIP_PORT']

    v.vm.network :private_network, ip: "10.2.2.2", auto_config: false
    v.vm.network :private_network, ip: "10.2.3.2", auto_config: false

    v.vm.provider :virtualbox do |p|
      # Required for >8 network interfaces
      p.customize ["modifyvm", :id, "--chipset", "ich9"]

      p.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      p.customize ["modifyvm", :id, "--memory", 4096]
      p.customize ["modifyvm", :id, "--cpus", 2]
      p.customize ["modifyvm", :id, "--name", ENV['BIGIP_NAME']]

      # NICs need to be virtio because BIG-IP doesn't have drivers for
      # the others
      p.customize ["modifyvm", :id, "--nic1", "nat"]
      p.customize ["modifyvm", :id, "--nictype1", "virtio"]
      p.customize ["modifyvm", :id, "--nic2", "hostonly"]
      p.customize ["modifyvm", :id, "--nictype2", "virtio"]
      p.customize ["modifyvm", :id, "--nic3", "hostonly"]
      p.customize ["modifyvm", :id, "--nictype3", "virtio"]
    end

    v.vm.provision "shell", inline: <<-SHELL
#{WAIT_FOR_BIGIP}

      tmsh load /sys config default
      sleep 10
      /usr/local/bin/SOAPLicenseClient --basekey  #{ENV['BIGIP_LICENSE']}
      sleep 10

      #{WAIT_FOR_BIGIP}

      tmsh modify sys dns name-servers replace-all-with { 10.0.2.3 }
      tmsh modify sys db setup.run value false
      tmsh create net vlan net1 interfaces add { 1.1 }
      tmsh create net self net1 address 10.2.2.2/255.255.255.0 vlan net1
      tmsh create net vlan net2 interfaces add { 1.2 }
      tmsh create net self net2 address 10.2.3.2/255.255.255.0 vlan net2
      tmsh save sys config
    SHELL
  end
end